In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Random Forest on Company dataset

# company = pd.read_csv("Company_Data.csv")

In [3]:
company["Sales"].unique()

array([ 9.5 , 11.22, 10.06,  7.4 ,  4.15, 10.81,  6.63, 11.85,  6.54,
        4.69,  9.01, 11.96,  3.98, 10.96, 11.17,  8.71,  7.58, 12.29,
       13.91,  8.73,  6.41, 12.13,  5.08,  5.87, 10.14, 14.9 ,  8.33,
        5.27,  2.99,  7.81, 13.55,  8.25,  6.2 ,  8.77,  2.67, 11.07,
        8.89,  4.95,  6.59,  3.24,  2.07,  7.96, 10.43,  4.12,  4.16,
        4.56, 12.44,  4.38,  3.91, 10.61,  1.42,  4.42,  7.91,  6.92,
        4.9 ,  6.85, 11.91,  0.91,  5.42,  5.21,  8.32,  7.32,  1.82,
        8.47,  7.8 ,  8.85, 13.39,  7.99,  9.46,  6.5 ,  5.52, 12.61,
        8.55, 10.64,  7.7 ,  4.43,  9.14,  8.01,  7.52, 11.62,  2.23,
        8.7 , 11.7 ,  6.56,  7.95,  5.33,  4.81,  4.53,  8.86,  8.39,
        5.58,  9.48,  7.45, 12.49,  4.88,  4.11,  5.3 ,  5.07,  4.62,
        5.55,  0.16,  3.47,  8.98,  9.  ,  6.62,  6.67,  6.01,  9.31,
        8.54,  8.8 ,  7.57,  7.37,  6.87, 11.67,  6.88,  8.19,  8.87,
        9.34, 11.27,  6.52,  4.96,  4.47,  8.41,  9.54,  7.62,  3.67,
        6.44,  5.17,

In [4]:
company["Sales"].value_counts()

7.80     4
6.67     3
8.77     3
9.32     3
5.87     3
        ..
8.89     1
13.39    1
9.14     1
5.07     1
9.50     1
Name: Sales, Length: 336, dtype: int64

In [5]:
np.median(company["Sales"])

7.49

In [6]:
company["sales"]="<=7.49"
company.loc[company["Sales"]>=7.49,"sales"]=">=7.49"

In [7]:
company.drop(["Sales"],axis=1,inplace=True)

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column_names in company.columns:
    if company[column_names].dtype == object:
        company[column_names]= le.fit_transform(company[column_names])
    else:
        pass

In [9]:
featues = company.iloc[:,0:10]
labels = company.iloc[:,10]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(featues,labels,test_size = 0.3,stratify = labels) 

In [12]:
y_train.value_counts()

1    141
0    139
Name: sales, dtype: int64

In [13]:
y_test.value_counts()

1    60
0    60
Name: sales, dtype: int64

In [14]:
from sklearn.ensemble import RandomForestClassifier as RF

In [15]:
model =RF(n_jobs=4,n_estimators = 150, oob_score =True,criterion ='entropy') 
model.fit(x_train,y_train)
model.oob_score_

0.7357142857142858

In [16]:
pred_train = model.predict(x_train)

In [18]:
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train,pred_train)
accuracy_train

1.0

In [19]:
from sklearn.metrics import confusion_matrix
con_train = confusion_matrix(y_train,pred_train)

In [20]:
pred_test = model.predict(x_test)

In [21]:
accuracy_test = accuracy_score(y_test,pred_test)

In [22]:
np.mean(y_test==pred_test)

0.8416666666666667

In [24]:
con_test = confusion_matrix(y_test,pred_test)
con_test

array([[52,  8],
       [11, 49]], dtype=int64)

# Random Forest on Fraud Dataset 

In [26]:
fraud = pd.read_csv("Fraud_check.csv")

In [27]:
fraud["income"]="<=30000"
fraud.loc[fraud["Taxable.Income"]>=30000,"income"]="Good"
fraud.loc[fraud["Taxable.Income"]<=30000,"income"]="Risky"

In [28]:
fraud.drop(["Taxable.Income"],axis=1,inplace=True)

In [29]:
fraud.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population","Work.Experience":"experience","Urban":"urban"},inplace=True)

In [30]:
for column_name in fraud.columns:
    if fraud[column_name].dtype == object:
        fraud[column_name] = le.fit_transform(fraud[column_name])
    else:
        pass

In [31]:
features = fraud.iloc[:,0:5]
labels = fraud.iloc[:,5]

In [32]:
colnames = list(fraud.columns)
predictors = colnames[0:5]
target = colnames[5]

In [33]:
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2,stratify = labels)

In [34]:
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

C:\Users\sohai\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\sohai\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [36]:
model.oob_score_

0.7395833333333334

In [37]:
prediction = model.predict(x_train)

In [38]:
accuracy = accuracy_score(y_train,prediction)
accuracy

0.99375

In [39]:
np.mean(prediction == y_train)

0.99375

In [41]:
confusion = confusion_matrix(y_train,prediction)
confusion

array([[381,   0],
       [  3,  96]], dtype=int64)

In [42]:
pred_test = model.predict(x_test)

In [43]:
acc_test =accuracy_score(y_test,pred_test)
acc_test

0.7333333333333333